spring.application.name=stayfinder

spring.datasource.url=jdbc:postgresql://localhost:5432/stayfinder
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=stayfinder

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


jwt.secret=stayfinder-super-secret-key-must-be-at-least-32-chars
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=600000


spring.jpa.open-in-view=false

spring.elasticsearch.uris=http://localhost:9200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=falak.khandec0043@gmail.com
spring.mail.password=oaam gpls ljyn gvvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25



springdoc.swagger-ui.operationsSorter=method

springdoc.api-docs.path=/v3/api-docs
spring.mvc.webjars.path-pattern=/webjars/**
springdoc.swagger-ui.path=/swagger-ui.html